//health check

### 

GET http://localhost:8000/health


### Get all users
GET http://localhost:8000/api/user

### GET user by ID

GET http://localhost:8000/api/user/12

### CREATE NEW USER

POST http://localhost:8000/api/users
Content-Type: application/json

{
    "Username": "Jamie404",
    "Email": "Jamie@Lannister.com",
    "Password": "JamieLannister",
    "TagName": "Kingslayer",
    "Location": "KingsLanding"
}

### Update a user
PUT http://localhost:8000/api/users/5
Content-Type: application/json

{
    
    "Username": "Khaleesi",
    "Email": "Khaleesi@momdragons.com",
    "Password": "khaleesi00",
    "TagName": "MotherOfDragons",
    "Location": "Nyeri"
}

### Delete a user
DELETE http://localhost:8000/api/users/12

### Get all groups
GET http://localhost:8000/api/groups

### Get Group by ID
GET http://localhost:8000/api/groups/3

### create group
POST http://localhost:8000/api/groups
Content-Type: application/json

{
    "GroupName": "Coldplay",
    "Description": "Grammy winning band from the UK",
    "CreatedDate": "2024-02-15"
}

### update group
PUT http://localhost:8000/api/groups/2
Content-Type: application/json

{
    "GroupName": "21 Pilots",
    "Description": "Dynamic duo from the US",
    "CreatedDate": "2004-04-03"
}

### Delete a group
DELETE http://localhost:8000/api/groups/3

### Get all events
GET http://localhost:8000/api/events

### Get event by ID
GET http://localhost:8000/api/events/1

### Get Messages
GET http://localhost:8000/api/messages

### GET messages by ID
GET http://localhost:8000/api/messages/12