//health check

### 

GET http://localhost:8000/health


### Get all users
GET http://localhost:8000/api/user

### GET user by ID

GET http://localhost:8000/api/user/5

### CREATE NEW USER

POST http://localhost:8000/api/users
Content-Type: application/json

{
    "Username": "Tyrion404",
    "Email": "Tyrion@Lannister.com",
    "Password": "TyrionLannister",
    "TagName": "Kingshand",
    "Location": "KingsLanding"
}

### Update a user
PUT http://localhost:8000/api/users/8
Content-Type: application/json

{
    
    "Username": "BrienneTarth",
    "Email": "Brienne@tarth.com",
    "Password": "Briennetarth00",
    "TagName": "MamaKnight",
    "Location": "Winterfell"
}

### Delete a user
DELETE http://localhost:8000/api/users/1002

### Get all groups
GET http://localhost:8000/api/groups

### Get Group by ID
GET http://localhost:8000/api/groups/1

### create group
POST http://localhost:8000/api/groups
Content-Type: application/json

{
    "GroupName": "Coldplay",
    "Description": "Grammy winning band from the UK",
    "CreatedDate": "2024-02-15"
}

### update group
PUT http://localhost:8000/api/groups/2
Content-Type: application/json

{
    "GroupName": "21 Pilots",
    "Description": "Dynamic duo from the US",
    "CreatedDate": "2004-04-03"
}

### Delete a group
DELETE http://localhost:8000/api/groups/1002

### Get all events
GET http://localhost:8000/api/events

### Get event by ID
GET http://localhost:8000/api/events/4

### create event
POST http://localhost:8000/api/events
Content-Type: application/json

{
    "EventName": "Octoberfest",
    "Description": "The ultimate beer festival for local music fans",
    "EventDate": "2024-10-20",
    "Location": "NgongRacecourse",
    "EventPosterURL": "sampleUrl"
}

### Update event
PUT http://localhost:8000/api/events/4
Content-Type: application/json

{
    "EventName": "Octoberfest",
    "Description": "The ultimate beer festival for local music fans",
    "EventDate": "2024-10-21",
    "Location": "NgongRacecourse",
    "EventPosterURL": "sampleUrlEditedToo"
}

### Delete event
DELETE http://localhost:8000/api/events/1002 

### Get Messages
GET http://localhost:8000/api/messages

### GET messages by ID
GET http://localhost:8000/api/messages/1003

### Create new message
POST http://localhost:8000/api/messages
Content-Type: application/json

{
    "SenderID": 2,
    "ReceiverID": 3,
    "MessageDate": "2024-02-16",
    "Content": "Did you see what I done, came in a black Benz, left in a white one"
}

### Update a message
PUT http://localhost:8000/api/messages/1003
Content-Type: application/json

{
    "SenderID": 3,
    "ReceiverID": 2,
    "MessageDate": "2024-02-15",
    "Content": "I'm just a hoodlum"
}

### Delete a message
DELETE http://localhost:8000/api/messages/1003 

###Get posts
GET http://localhost:8000/api/posts

### Get Post by ID
GET http://localhost:8000/api/posts/2

### Create Post
POST http://localhost:8000/api/posts
Content-Type: application/json

{
    "UserID": 1,
    "Content": "Just came back from Jamaica",
    "PostDate": "2024-02-16",
    "Likes": 69,
    "Comments": 50
}

### Update post
PUT http://localhost:8000/api/posts/1002
Content-Type: application/json

{
    "UserID": 1,
    "Content": "Just came back from Jamaica. Tan almost everywhere. Jan almost everywhere",
    "PostDate": "2024-02-16",
    "Likes": 69,
    "Comments": 54
}

### Delete Post
DELETE http://localhost:8000/api/posts/1002

### Get all friendships
GET http://localhost:8000/api/friendships

### Get Friendships by FriendshipID
GET http://localhost:8000/api/friendships/1002

### Get all friends of a user
GET http://localhost:8000/api/friends/1

### Create new friendship
POST http://localhost:8000/api/friendships
Content-Type: application/json

{
   "User1ID": 2,
   "User2ID": 3,
   "FriendshipDate": "2024-02-16" 
}

###
DELETE http://localhost:8000/api/friendships/1

### GET all photos
GET http://localhost:8000/api/photos

### Get Photo by ID
GET http://localhost:8000/api/photos/1003

### Create photo
POST http://localhost:8000/api/photos
Content-Type: application/json

{
    "UserID": 1,
    "PhotoURL": "url4",
    "UploadDate": "2024-01-18"
}

### Update a photo
PUT http://localhost:8000/api/photos/1003
Content-Type: application/json

{
    "UserID": 1,
    "PhotoURL": "url4edited",
    "UploadDate": "2024-02-18"
}

### Delete a photo
DELETE http://localhost:8000/api/photos/1002

### Get comments
GET http://localhost:8000/api/comments

### Get Comments by CommentID
GET http://localhost:8000/api/comments/2

### Get comments for a particular post
GET http://localhost:8000/api/3/comments

### Create a comment
POST http://localhost:8000/api/comments
Content-Type: application/json

{
    "PostID": 3,
    "UserID": 2,
    "CommentDate": "2024-02-19",
    "Content": "User 2 comments on post 3"

}

### Update comment
PUT http://localhost:8000/api/comments/1
Content-Type: application/json

{
    "PostID": 1,
    "UserID": 2,
    "CommentDate": "2024-02-20",
    "Content": "Updated comment on post 1"
}

### Delete comment
DELETE http://localhost:8000/api/comments/1002

### Get all eventattendees
GET http://localhost:8000/api/eventattendees

### Get attendees of an event
GET http://localhost:8000/api/eventattendees/2

### Get events attended by a user
GET http://localhost:8000/api/4/eventattendees/

### Create new eventAttendee entry
POST http://localhost:8000/api/eventattendees/
Content-Type: application/json

{
    "EventID": 4,
    "AttendeeID": 4
}

### Delete event attendee entry
DELETE http://localhost:8000/api/eventattendees/4/4